---
- name: Install Java 17 - RedHat (Amazon Linux, RHEL, CentOS)
  ansible.builtin.yum:
    name: java-17-amazon-corretto
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install Java 17 - Debian/Ubuntu
  ansible.builtin.apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Set Java 17 as default (RedHat)
  ansible.builtin.command: alternatives --set java /usr/lib/jvm/java-17-amazon-corretto.x86_64/bin/java
  when: ansible_os_family == 'RedHat'

- name: Set Java 17 as default (Debian/Ubuntu)
  ansible.builtin.command: update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
  when: ansible_os_family == 'Debian'

- name: Add Jenkins repo
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  when: ansible_os_family == 'RedHat'

- name: Import Jenkins repo key (RedHat)
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  when: ansible_os_family == 'RedHat'

- name: Add Jenkins APT key (Debian/Ubuntu)
  ansible.builtin.apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Jenkins APT repository (Debian/Ubuntu)
  ansible.builtin.apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Jenkins and git (RedHat)
  ansible.builtin.yum:
    name:
      - jenkins
      - git
      - unzip
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install Jenkins and git (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - jenkins
      - git
      - unzip
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Ensure Jenkins is started and enabled
  ansible.builtin.systemd:
    name: jenkins
    enabled: yes
    state: restarted
