---
- name: Update apt cache (Debian family)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Update yum cache (RedHat family)
  ansible.builtin.yum:
    name: '*'
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Ensure python3 and pip are installed
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present
